[package]
name = "coolcolors-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termsize = "0.1"
crossterm = "0.26.1"
device_query = "1.1.1"

